---
# Allow access to Samba through firewall for specified networks
# If samba_allow is undefined or False, allow access from all
samba_allow: []

samba_workgroup: 'WORKGROUP'
samba_netbios_name: '{{ ansible_hostname }}'
samba_server_string: '%h file server'

# Name of the /etc/init.d/ service script
samba_service_name: 'smb'

# Which hash variable is used to configure [global] section in smb.conf
samba_global: '{{ samba_default_global }}'

# You can specify additional options in a separate hash
samba_global_custom: False

# Which hash of hashes is used to configure shares in smb.conf
samba_shares: '{{ samba_default_shares }}'

# Default [global] configuration
samba_default_global:

  # Browsing / Identification
  workgroup: '{{ samba_workgroup | default("WORKGROUP") }}'
  netbios_name: '{{ samba_netbios_name | default(ansible_hostname) }}'
  server_string: '{{ samba_server_string | default("%h file server") }}'

  # Authentication
  security: 'user'
  passdb_backend: 'tdbsam'

  # Disable printing by default
  printing: 'bsd'
  load_printers: 'no'
  printcap_name: '/dev/null'
  show_add_printer_wizard: 'no'
  disable_spoolss: 'yes'


# Hash of hashes of default shares
samba_default_shares:

  'homes':
    comment: 'Home Directories'
    browseable: 'no'
    writable: 'yes'
