---
- name: Mount CTDB reclock volume
  mount: name=/gluster/lock src=localhost:/ctdb fstype=glusterfs opts=_netdev,defaults,direct-io-mode=enable,transport=tcp,xlator-option=*client*.ping-timeout=10 state=mounted

- name: Stop all Samba services minus CTDB
  service: name={{item.name}} state={{item.state}}
  with_items:
    - { name: 'smb', state: 'stopped' }
    - { name: 'nmb', state: 'stopped' }
    - { name: 'winbind', state: 'stopped' }
    - { name: 'ctdb', state: 'restarted' }

- name: Verify CTDB is healthy
  shell: while true; do sleep 1; status=$(ctdb status 2>/dev/null); rc=$?; if [ $rc -ne 0 ]; then exit $rc; fi; if ! echo $status | grep -qs 'UNHEALTHY (THIS'; then exit; fi; done

- name: Configure DNS for Active Directory
  template: src={{item.src}} dest={{item.dest}} owner=root group=root mode=0744
  with_items:
    - { src: 'files/99-no-dns.conf', dest: '/etc/NetworkManager/conf.d/99-no-dns.conf' }
    - { src: 'files/resolv.conf.j2', dest: '/etc/resolv.conf' }

- name: Restart NetworkManager
  service: name="NetworkManager" state=restarted

- name: Configure nsswitch
  shell: sed -ri '/^(passwd|group)/s/$/ winbind/' /etc/nsswitch.conf

- name: Join Active Directory domain
  shell: net join -U Administrator%redhat
  run_once: true
  delegate_to: "{{ groups['smb_servers'][0] }}"

- name: Register Active Directory DNS
  shell: "net ads -P dns register {{ ha_name }}.{{ ad_domain }} {{ vips|join(' ') }}"
#  shell: net ads -P dns register storage-ha.jarrpa.net 192.168.122.111 192.168.122.112
  run_once: true
  delegate_to: "{{ groups['smb_servers'][0] }}"

- name: Verify Active Directory domain membership
  shell: net ads testjoin
  run_once: true
  delegate_to: "{{ groups['smb_servers'][0] }}"

- name: Stop CTDB
  service: name={{item.name}} state={{item.state}}
  with_items:
    - { name: 'ctdb', state: 'stopped' }

- name: Unmount CTDB reclock volume
  mount: name=/gluster/lock src=localhost:/ctdb fstype=glusterfs state=unmounted

