---
- hosts: all
  name: Raw Installation (RedHat/Fedora)
  sudo: yes
  gather_facts: False

  tasks:
    - name: Make sure playbook dependencies are installed
      raw: >
        for REPO in `find /vagrant/playbooks -name '*.repo'`; do
          cp $REPO /etc/yum.repos.d/;
        done;
        dnf install -y --best {{ install_pkgs }}
