---
# file: samba_servers.yml
- hosts: all
  name: Initializing
  sudo: yes

  tasks:
    - name: Detect guest OS family
      group_by: key={{ ansible_os_family }}
      changed_when: False

    - name: Set hostname
      hostname: "name={{ inventory_hostname }}{% if ad['domain'] is defined and ad['domain'] %}.{{ ad['domain'] }}{% endif %}"

    - name: Disable SELinux
      selinux: state=disabled

- hosts: RedHat
  name: Server Setup (RedHat)
  sudo: yes
  gather_facts: False

  tasks:
#    - include: roles/common/tasks/setup-RedHat.yml

- hosts: none
  name: Server Setup (Common)
  sudo: yes

  roles:
    - common

  vars:
    - firewall_services:
      - ssh
      - samba
      - samba-client
    - firewall_ports:
      - '4379/tcp'
    - firewall_interfaces:
      - 'eth0'
      - 'eth1'

- hosts: samba_servers
  name: Server Setup (SMB)
  sudo: yes

#  roles:
#    - samba

  tasks:
    - name: Copy CTDB config files
      template: src={{item.src}} dest={{item.dest}} owner=root group=root mode=0744
      with_items:
        - { src: "{% if ctdb['config'] is defined and ctdb['config'] %}{{ ctdb['config'] }}{% else %}'files/ctdb'{% endif %}", dest: '/etc/sysconfig/ctdb' }
        - { src: 'files/nodes.j2', dest: '/etc/ctdb/nodes' }
        - { src: 'files/public_addresses.j2', dest: '/etc/ctdb/public_addresses' }
      when: ctdb['setup_ctdb'] is defined and ctdb['setup_ctdb']

    - name: Copy Samba config files
      template: src={{item.src}} dest={{item.dest}} owner=root group=root mode=0744
      with_items:
        - { src: "files/smb.conf.j2", dest: '/etc/samba/smb.conf' }
      when: samba['setup_samba'] is defined and samba['setup_samba']

- hosts: ad_server
  name: Active Directory Setup
  sudo: yes

  tasks:
    - include: roles/samba/tasks/setup-AD.yml
      when: ad['setup_ad']

- hosts: all
  name: Start Services
  sudo: yes

  tasks:
    - name: Start Samba and Gluster services
      service: "name={{ item }} state=started enabled=yes"
      with_items: services
